export const GET_ALL_DOGS_URL = "http://localhost:3001/dogs";
export const GET_DOG_SEARCH = "http://localhost:3001/dogs/?name="
export const GET_ALL_TEMPERAMENTS_URL = "http://localhost:3001/temperaments";
export const GET_DOG_BY_ID = "http://localhost:3001/dogs/";
export const CREATE_NEW_DOG = "http://localhost:3001/dogs/add";
export const GET_ALL_DB_DOGS = "http://localhost:3001/dogs/getDB"
export const PENDING = "pending";
export const FULLFILLED = "fullfilled";
export const REJECTED = "rejected"